// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK1sGCWsOx-dIvIAeyuOrAgiHiJV019eQ',
    appId: '1:521043191592:web:6a0402a1c0844ad91a921d',
    messagingSenderId: '521043191592',
    projectId: 'supabase-56b6d',
    authDomain: 'supabase-56b6d.firebaseapp.com',
    storageBucket: 'supabase-56b6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwkhegslVNiriJrUlzxnXnmtA3BvL795k',
    appId: '1:521043191592:android:3fb91e77eb7c676d1a921d',
    messagingSenderId: '521043191592',
    projectId: 'supabase-56b6d',
    storageBucket: 'supabase-56b6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMVHfdy_tBzuNdioR4DR5c_53CFDrAFnk',
    appId: '1:521043191592:ios:3ca797552d01e72c1a921d',
    messagingSenderId: '521043191592',
    projectId: 'supabase-56b6d',
    storageBucket: 'supabase-56b6d.firebasestorage.app',
    iosBundleId: 'com.example.iClickApp',
  );
}
